---
version: "2.1"
services:
  jacketttest:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jacketttest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=false #optional
#      - RUN_OPTS=<run options here> #optional
#    volumes:
#      - /app
#      - <path to blackhole>:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
